from typing import Dict, List, Optional, Union

def flesch_reading_ease(text: str) -> float: ...
def flesch_kincaid_grade(text: str) -> float: ...
def smog_index(text: str) -> float: ...
def coleman_liau_index(text: str) -> float: ...
def automated_readability_index(text: str) -> float: ...
def dale_chall_readability_score(text: str) -> float: ...
def linsear_write_formula(text: str) -> float: ...
def gunning_fog(text: str) -> float: ...
def text_standard(text: str, float_output: bool = False) -> Union[str, float]: ...
def fernandez_huerta(text: str) -> float: ...
def szigriszt_pazos(text: str) -> float: ...
def gutierrez_polini(text: str) -> float: ...
def crawford(text: str) -> float: ...
def gulpease_index(text: str) -> float: ...
def osman(text: str) -> float: ...
def lexicon_count(text: str, removepunct: bool = True) -> int: ...
def sentence_count(text: str) -> int: ...
def syllable_count(text: str, lang: str = 'en_US') -> int: ...
def avg_sentence_length(text: str) -> float: ...
def avg_syllables_per_word(text: str) -> float: ...
def avg_letter_per_word(text: str) -> float: ...
def avg_sentence_per_word(text: str) -> float: ...
def difficult_words(text: str, syllable_threshold: int = 2) -> int: ...
def poly_syllable_count(text: str) -> int: ...
def syllables_per_word(text: str) -> Dict[str, int]: ...
def monosyllabcount(text: str) -> int: ...
def set_lang(lang_id: str) -> None: ...
def set_locale(locale: str) -> None: ...
def textstat(text: str) -> Dict[str, float]: ...